CREATE TABLE games (
  lichess_id VARCHAR,
  tournament VARCHAR,
  movedata BLOB,
  clocks_white USMALLINT[],
  clocks_black USMALLINT[],
  evals SMALLINT[],
  ply_count USMALLINT,
  white VARCHAR,
  black VARCHAR,
  white_rating SMALLINT,
  black_rating SMALLINT,
  time_initial USMALLINT,
  time_increment UTINYINT,
  result VARCHAR,
  termination VARCHAR,
  white_rating_diff SMALLINT,
  black_rating_diff SMALLINT,
  eco VARCHAR,
  opening VARCHAR,
  white_title VARCHAR,
  black_title VARCHAR,
  utc_timestamp TIMESTAMP
);